### ISSUE TITLE
Wouldn't override existing filetypes

### ISSUE THREAD

**Issue by agzam** [jixiuf/dired-filetype-face#8]
I wanted to make certain filetypes of different (than default) colors, but it doesn't work, e.g:

```
(deffiletype-face "js" "goldenrod")
(deffiletype-face-regexp js :extensions '("js" "json"))
(deffiletype-setup "js")
```

**Comment by PhilHudson** [comment]
Your code sample works for me exactly as expected: JavaScript files listed in goldenrod in dired. 

To help you out with this, please answer two standard bug-description questions:

1. What are you seeing that you don't expect, or not seeing that you do expect?

2. What version of Emacs are you using?

Also, in this case, have you tried `M-x customize-variable RET dired-filetype-js-regexp` and `M-x customize-face RET dired-filetype-js`? What do you see?

**Comment by PhilHudson** [comment]
I see the problem now: duplicate settings, as indeed your bug title implies with "override". I think it's an ordering issue. Should be as simple as adding `'append` to the `add-hook` in the setup macro.

**Comment by PhilHudson** [comment]
In the meantime, a (not very satisfactory) workaround:
1. `M-x customize-variable RET dired-filetype-plain-regexp` and remove "json"
2. `M-x customize-variable RET dired-filetype-xml-regexp` and remove "js"

**Comment by agzam** [comment]
`customize-variable` is for zombies. I used `(setq dired-filetype-xml-regexp (remove "js" dired-filetype-xml-regexp)`

**Comment by jixiuf** [comment]
and now js and json are added to dired-filetype-face.el
with your setting 

```
(deffiletype-face "js" "goldenrod")
(deffiletype-face-regexp js :extensions '("js" "json"))
(deffiletype-setup "js")
```

**Comment by agzam** [comment]
Awesome! Thanks.

**Comment by PhilHudson** [comment]
On Tue, 16 Feb 2016 at 10:58:32 pm GMT, Ag Ibragimov notifications@github.com wrote:

> customize-variable is for zombies. I used (setq dired-filetype-xml-regexp
> (remove "js" dired-filetype-xml-regexp)
> 
> —
> Reply to this email directly or view it on GitHub.

Neatly done!

## 

Phil Hudson                   http://hudson-it.ddns.net
@UWascalWabbit                 PGP/GnuPG ID: 0x887DCA63
